// Host test stub: VIC colour numbers as in Oscar64 include/c64/vic.h
enum VICColors
{
    VCOL_BLACK, VCOL_WHITE, VCOL_RED, VCOL_CYAN, VCOL_PURPLE, VCOL_GREEN, VCOL_BLUE, VCOL_YELLOW,
    VCOL_ORANGE, VCOL_BROWN, VCOL_LT_RED, VCOL_DARK_GREY, VCOL_MED_GREY, VCOL_LT_GREEN, VCOL_LT_BLUE, VCOL_LT_GREY
};
