#!/usr/bin/env python3
"""
DMBoot 128 v5 - Petmate9 splash screen to C data

Converts the two screens of a Petmate9 workspace (a 40x25 VIC screen,
charset c128Upper or c128Lower, and an 80x25 VDC screen, charset c128vdc)
into packed C arrays for the splash overlay (src/splash.c):
- VIC: screen codes and colours (1000 bytes each)
- VDC: screen codes and attributes (2000 bytes each)
each packed with PackBits: a control byte n < 128 is followed by n + 1
literal bytes; n >= 128 repeats the next byte 257 - n times (2..129).

Usage: python3 tools/petmate2c.py <splash.petmate> <output.c>

Code and resources from others used:
-   Petmate9 by wbochar, based on Petmate by Janne Hellsten
    (https://github.com/wbochar/petmate9): workspace file format (version 4).
    Adapted: only reads the file layout; nothing of its code is used.
"""

import json
import sys

VDC_CHARSET = "c128vdc"
VIC_LOWER_CHARSETS = ("c128Lower", "lower")
RUN_MIN, RUN_MAX, LITERAL_MAX = 2, 129, 128


def packbits(data):
    out = []
    i = 0
    while i < len(data):
        run = 1
        while i + run < len(data) and run < RUN_MAX and data[i + run] == data[i]:
            run += 1
        if run >= RUN_MIN:
            out += [257 - run, data[i]]
            i += run
            continue
        start = i
        while i < len(data) and i - start < LITERAL_MAX:
            if i + 1 < len(data) and data[i + 1] == data[i]:
                break
            i += 1
        out += [i - start - 1] + data[start:i]
    return out


def unpack(packed, size):
    """Reference decoder, used to check the output."""
    out = []
    i = 0
    while len(out) < size:
        n = packed[i]
        if n < 128:
            out += packed[i + 1:i + 2 + n]
            i += n + 2
        else:
            out += [packed[i + 1]] * (257 - n)
            i += 2
    return out


def c_array(name, data):
    lines = [f"const char {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    workspace = json.load(open(sys.argv[1]))
    vic = next(f for f in workspace["framebufs"] if f["charset"] != VDC_CHARSET and f["width"] == 40)
    vdc = next(f for f in workspace["framebufs"] if f["charset"] == VDC_CHARSET)

    streams = {
        "splash_vic_codes": [c["code"] & 0xff for row in vic["framebuf"] for c in row],
        "splash_vic_colours": [c["color"] & 0x0f for row in vic["framebuf"] for c in row],
        "splash_vdc_codes": [c["code"] & 0xff for row in vdc["framebuf"] for c in row],
        "splash_vdc_attrs": [(c["attr"] if "attr" in c else c["color"]) & 0xff
                             for row in vdc["framebuf"] for c in row],
    }
    packed = {}
    for name, data in streams.items():
        packed[name] = packbits(data)
        assert unpack(packed[name], len(data)) == data, name

    out = [
        "/*",
        "DMBoot 128 v5 - Splash screen data",
        "",
        f"Generated by tools/petmate2c.py from {sys.argv[1]}; do not edit.",
        "Edit the Petmate9 file and run 'make' (or the tool) again.",
        "Streams are packed with PackBits (see src/splash.c).",
        "*/",
        "",
        f"const char splash_vic_border = {vic['borderColor'] & 0x0f};",
        f"const char splash_vic_background = {vic['backgroundColor'] & 0x0f};",
        f"const char splash_vic_lowercase = {1 if vic['charset'] in VIC_LOWER_CHARSETS else 0};",
        f"const char splash_vdc_background = {vdc['backgroundColor'] & 0x0f};",
        "",
    ]
    for name, data in packed.items():
        out.append(c_array(name, data))
        out.append("")
    with open(sys.argv[2], "w") as f:
        f.write("\n".join(out))
    total = sum(len(p) for p in packed.values())
    print(f"{sys.argv[2]}: {total} bytes packed ({sum(len(d) for d in streams.values())} unpacked)")


if __name__ == "__main__":
    main()
